# Generated by Django 3.1.3 on 2020-11-28 11:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_update', models.DateField(default=datetime.date(2020, 11, 28))),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Overtime_skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateField(default=datetime.date(2020, 11, 28))),
                ('counter', models.IntegerField()),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsgraph.language')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsgraph.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Overtime_jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
                ('data_created', models.DateField(default=datetime.date(2020, 11, 28))),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsgraph.language')),
            ],
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsgraph.language')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsgraph.skill')),
            ],
        ),
    ]
