# Generated by Django 3.1.3 on 2020-11-28 11:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skillsgraph', '0003_auto_20201128_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overtime_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
                ('data_created', models.DateField(default=datetime.datetime(2020, 11, 28, 11, 42, 52, 511263, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Overtime_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateField(default=datetime.datetime(2020, 11, 28, 11, 42, 52, 511636, tzinfo=utc))),
                ('counter', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='overtime_skills',
            name='language_id',
        ),
        migrations.RemoveField(
            model_name='overtime_skills',
            name='skill_id',
        ),
        migrations.AlterField(
            model_name='language',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2020, 11, 28, 11, 42, 52, 510160, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Overtime_jobs',
        ),
        migrations.DeleteModel(
            name='Overtime_skills',
        ),
        migrations.AddField(
            model_name='overtime_skill',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsgraph.language'),
        ),
        migrations.AddField(
            model_name='overtime_skill',
            name='skill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsgraph.skill'),
        ),
        migrations.AddField(
            model_name='overtime_job',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsgraph.language'),
        ),
    ]
