# Generated by Django 3.1.3 on 2020-11-28 11:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skillsgraph', '0004_auto_20201128_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2020, 11, 28, 11, 51, 47, 320980, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='overtime_job',
            name='data_created',
            field=models.DateField(default=datetime.datetime(2020, 11, 28, 11, 51, 47, 322052, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='overtime_skill',
            name='data_created',
            field=models.DateField(default=datetime.datetime(2020, 11, 28, 11, 51, 47, 322431, tzinfo=utc)),
        ),
    ]
