# Generated by Django 3.1.3 on 2020-11-28 12:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skillsgraph', '0005_auto_20201128_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2020, 11, 28, 12, 46, 24, 779602, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='overtime_job',
            name='data_created',
            field=models.DateField(default=datetime.datetime(2020, 11, 28, 12, 46, 24, 780675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='overtime_skill',
            name='data_created',
            field=models.DateField(default=datetime.datetime(2020, 11, 28, 12, 46, 24, 781092, tzinfo=utc)),
        ),
    ]
