# Generated by Django 3.1.3 on 2020-11-28 13:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skillsgraph', '0006_auto_20201128_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtime_job',
            name='data_created',
        ),
        migrations.RemoveField(
            model_name='overtime_skill',
            name='data_created',
        ),
        migrations.AddField(
            model_name='overtime_job',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 11, 28, 13, 20, 55, 399776, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='overtime_skill',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 11, 28, 13, 20, 55, 400151, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='language',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2020, 11, 28, 13, 20, 55, 398718, tzinfo=utc)),
        ),
    ]
