# Generated by Django 3.1.3 on 2020-11-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillsgraph', '0017_auto_20201128_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtime_job',
            name='language_id',
        ),
        migrations.RemoveField(
            model_name='overtime_skill',
            name='language_id',
        ),
        migrations.RemoveField(
            model_name='overtime_skill',
            name='skill_id',
        ),
        migrations.DeleteModel(
            name='Count',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Overtime_job',
        ),
        migrations.DeleteModel(
            name='Overtime_skill',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
